language: cpp
compiler:
    - clang
notifications:
    email: false
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/julianightlies -y
    - sudo apt-get update -qq -y
    - sudo apt-get install libpcre3-dev julia -y
script:
    - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir())/GeneticAlgorithms`); Pkg.resolve()'
    - julia -e 'using GeneticAlgorithms; @assert isdefined(:GeneticAlgorithms); @assert typeof(GeneticAlgorithms) === Module'
    - julia -e 'require("test/testga.jl"); test_serial(); test_parallel()'
